"use client";

import { useState } from "react";
import { Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";
import { useSharedProjectSource } from "@/lib/project/store";

// First-run helper: "Try a sample" drops a bundled PNG into the shared
// source so users can see the tool actually working without having to find
// a sprite of their own.
//
// Samples live under public/samples/, generated by scripts/generate-samples.mjs.

const SAMPLES = [
  { file: "character.png", label: "Character", hint: "64×64 single sprite" },
  { file: "sheet.png", label: "5×5 sheet", hint: "25 varied frames" },
  { file: "pterodactyl.png", label: "Pterodactyl", hint: "4×4 thin-limbed" },
];

interface SampleSpritesProps {
  className?: string;
}

export function SampleSprites({ className }: SampleSpritesProps) {
  const { sourceFile, setSharedSource } = useSharedProjectSource();
  const [loading, setLoading] = useState<string | null>(null);

  // Only show when the user has no source loaded — once they upload or
  // pick a sample the choices are redundant.
  if (sourceFile) return null;

  const load = async (name: string) => {
    setLoading(name);
    try {
      const res = await fetch(`/samples/${name}`);
      const blob = await res.blob();
      const file = new File([blob], name, { type: "image/png" });
      await setSharedSource(file);
    } finally {
      setLoading(null);
    }
  };

  return (
    <div className={cn("text-center text-xs text-muted-foreground space-y-2", className)}>
      <div className="flex items-center justify-center gap-1.5 uppercase tracking-wider text-[10px] font-semibold">
        <Sparkles className="w-3 h-3" />
        or try a sample
      </div>
      <div className="flex flex-wrap items-center justify-center gap-1.5">
        {SAMPLES.map((s) => (
          <button
            key={s.file}
            onClick={() => void load(s.file)}
            disabled={loading === s.file}
            className={cn(
              "inline-flex items-center gap-1 px-2 py-1 rounded-md border bg-background hover:border-primary/40 hover:bg-accent/40 transition-colors text-[11px]",
              loading === s.file && "opacity-50",
            )}
            title={s.hint}
          >
            <span className="font-medium">{s.label}</span>
            <span className="text-muted-foreground text-[9px]">{s.hint}</span>
          </button>
        ))}
      </div>
    </div>
  );
}
